### PR TITLE
v0.1.0

### PR DESCRIPTION
**Pull request by PuKoren**
# Features
- Add Application class
- Add IVR class and basic methods
- Add project structure and packagist package

### CODE REVIEW

**Comment by mrister** [comment]
Sorry, I don't  php experience to give for the code, aside from that LGTM.

**Comment by jkernech** [comment]
LGTM and most importantly very nice work :)

**Comment by ykhatal** [comment]
@PuKoren well architectured, you gave me the desire to jump on PHP :p 
LGTM

**Comment by PuKoren** [comment]
@ky23 come on the dark side

Darth

**Pull request merged**
